# minikube addons enable metrics-server
---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: limit-resources
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"
---
# kubectl top pod cpu-demo --namespace=limit-resources
