apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx

# kubectl run nginx --image=nginx --dry-run=client -oyaml >> nginx-pod.yaml
