apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: metallb
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - START-END
