apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp-color
  name: webapp-color
spec:
  containers:
  - image: kodekloud/webapp-color
    name: webapp-color
    env:
    - name: APP_COLOR
      value: pink
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: webapp-color
  name: webapp-color
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    run: webapp-color
  type: NodePort
