---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: webapp-config-map
data:
  APP_COLOR: darkblue
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp-color-cm
  name: webapp-color-cm
spec:
  containers:
  - image: kodekloud/webapp-color
    name: webapp-color
    envFrom:
    - configMapRef:
        name: webapp-config-map
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: webapp-color-cm
  name: webapp-color-cm
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31080
  selector:
    run: webapp-color-cm
  type: NodePort
