# kubectl create secret docker-registry secret-tiger-docker --docker-username=tiger --docker-password=pass113 --docker-email=tiger@acme.com --docker-server=my-registry.example:5000
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJteS1yZWdpc3RyeS5leGFtcGxlOjUwMDAiOnsidXNlcm5hbWUiOiJ0aWdlciIsInBhc3N3b3JkIjoicGFzczExMyIsImVtYWlsIjoidGlnZXJAYWNtZS5jb20iLCJhdXRoIjoiZEdsblpYSTZjR0Z6Y3pFeE13PT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: secret-tiger-docker
type: kubernetes.io/dockerconfigjson
